name: tgat_model
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.3
  - pandas=2.2.0
  - scikit-learn=1.3.0
  - scipy=1.11.2
  - matplotlib=3.7.3
  - seaborn=0.12.2
  - tqdm=4.66.1
  - jupyterlab
  - notebook
  - ipykernel
  # 注意：不包含 pytorch，請使用者依 CUDA 自行安裝
  - pip:
      - torch-geometric==2.6.1
      - torch-geometric-temporal==0.56.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-cluster==1.6.3
      - torch-spline-conv==1.2.2
      - pyg-lib==0.4.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - attrs==23.1.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.1.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - dask==2025.5.1
      - decorator==4.4.2
      - frozenlist==1.4.1
      - fonttools==4.47.2
      - fsspec==2023.6.0
      - gradient==2.0.6
      - gradient-utils==0.5.0
      - idna==3.3
      - importlib_metadata==8.7.0
      - jinja2==3.1.3
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - locket==1.0.0
      - multidict==6.0.4
      - networkx==3.2.1
      - packaging==23.2
      - partd==1.4.2
      - pillow==9.5.0
      - psutil==5.9.8
      - pyparsing==2.4.7
      - python-dateutil==2.8.2
      - pytz==2022.1
      - requests==2.31.0
      - sympy==1.12
      - threadpoolctl==3.2.0
      - toolz==1.0.0
      - triton==2.1.0
      - tzdata==2023.4
      - urllib3==2.0.7
      - wheel==0.45.1
      - yarl==1.9.4
      - zipp==3.21.0
